<?php

class Cylinder extends Circle
{
    public int $height;

    public function __construct($name, $radius, $height)
    {
        parent::__construct($name, $radius, $height);
        $this->height = $height;
    }

    public function caculateArea()
    {
        return parent::caculateArea() * 2 + parent::calculatePerimeter() * $this->height; // TODO: Change the autogenerated stub

    }

    public function calculateVolume()
    {
        return parent::caculateArea() * $this->height;
    }
}